version: "3"
services:
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: always
    ports: 
      - "8181:8181/tcp"
    environment:
      TZ: 'America/Bogota'
    volumes:
      - /home/pi/config/config/tautulli:/config
  radarr:
    image: linuxserver/radarr
    restart: always
    container_name: radarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    volumes:
      - /home/pi/Videos/Movies:/movies
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/radarr:/config
  sonarr:
    image: linuxserver/sonarr
    restart: always
    container_name: sonarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/Videos/Shows:/tvseries  
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/sonarr:/config
    ports:
      - 8989:8989
  bazarr:
    image: linuxserver/bazarr
    restart: always
    ports:
      - 6767:6767
    volumes:
      - /home/pi/Videos/Movies:/movies
      - /home/pi/Videos/Shows:/tv
      - /home/pi/config/config/bazarr:/config
  jackett:
    image: linuxserver/jackett
    restart: always
    ports:
      - 9117:9117
    volumes:
      - /home/pi/config/config/jackett:/config
  duplicati:
    image: duplicati/duplicati:linux-arm32v7-latest
    restart: always
    ports:
      - 8200:8200
    volumes:
      - /home/pi/config/config/duplicati:/data
      - /home/pi/config/config/:/home/config
  deluge:
    image: linuxserver/deluge
    restart: always
    ports:
      - 8113:8112
    volumes:
      - /home/pi/config/config/deluge:/config
      - /home/pi/completedTorrents:/downloads
  readarr:
    image: linuxserver/readarr:nightly
    restart: always
    container_name: readarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/Books:/books  
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/readarr:/config
    ports:
      - 8787:8787

