version: "3"
services:
  docker-swarm-visualizer:
    image: alexellis2/visualizer-arm
    container_name: visualizer-arm
    ports:
      - "8080:8080/tcp"
    volumes:
       - '/var/run/docker.sock:/var/run/docker.sock'
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: 'HpAtAmgw'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    environment:
      TZ: 'America/Bogota'
    restart: always
    network_mode: host
    volumes:
      - '/home/pi/Home-AssistantConfig:/config'

    
    
    
