version: "3"
services:
  docker-swarm-visualizer:
    image: alexellis2/visualizer-arm
    container_name: visualizer-arm
    ports:
      - "8080:8080/tcp"
    volumes:
       - '/var/run/docker.sock:/var/run/docker.sock'
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: 'HpAtAmgw'
      VIRTUAL_HOST: wendy
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    environment:
      TZ: 'America/Bogota'
    restart: always
    network_mode: host
    volumes:
      - '/home/pi/Home-AssistantConfig:/config'
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    ports: 
      - "8181:8181/tcp"
    environment:
      TZ: 'America/Bogota'
    restart: always
    network_mode: host
    volumes:
      - './config-tautulli/:/config/'
      - './plex_logs-tautulli/:/plex_logs/'
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    ports:
      - 7878:7878
  deluge:
    image: linuxserver/deluge
    ports:
      - "8112:8112"
    
    
    
