version: "3.3"
services:
  pihole:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - /home/pi/config/config/heimdall:/config
  rclone-heimdall:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-heimdall
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/heimdall/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/heimdall"]
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: vikunja
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: <a super secure random secret>
      VIKUNJA_SERVICE_FRONTENDURL: http://<your public frontend url with slash>/
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    image: vikunja/frontend
    ports:
      - 80:80
    environment:
      VIKUNJA_API_URL: http://<your-ip-here>:3456/api/v1
    restart: unless-stopped
