services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - /home/pi/config/config/heimdall:/config
  gnucash-db:
    image: postgres:13
    container_name: gnucash-db
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=gnucash
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/gnucash/db/:/backup
      - ./db-gnucash:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5433:5432"
  vikunja-db:
    image: postgres:13
    container_name: vikunja-db
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=vikunja
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/vikunja/db/:/backup
      - ./db-vikunja:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    environment:
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: <a super secure random secret>
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.montesj.dev/
      VIKUNJA_CORS_ENABLE: true
    ports:
      - 3456:3456
    volumes:
      - /home/pi/config/config/vikunja/files:/app/vikunja/files
    depends_on:
      - vikunja-db
    restart: unless-stopped
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: always
    ports: 
      - "8181:8181/tcp"
    environment:
      TZ: 'America/Bogota'
    volumes:
      - /home/pi/config/config/tautulli:/config
  rclone-vikunja-db:
    image: rclone/rclone
    restart: no
    container_name: rclone-vikunja-db
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/vikunja/db:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/vikunja/db"]
  rclone-gnucash-db:
    image: rclone/rclone
    restart: no
    container_name: rclone-gnucash-db
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/gnucash/db:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/gnucash/db"]
  rclone-vikunja-api:
    image: rclone/rclone
    restart: no
    container_name: rclone-vikunja-api
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/vikunja/files:/mnt/config
    command: ["sync","/mnt/config","jonomega:/Backup/rclone/vikunja/files"]
  rclone-pihole:
    image: rclone/rclone
    restart: no
    container_name: rclone-pihole
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/pihole-backup/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/pihole1"]
  rclone-tautulli:
    image: rclone/rclone
    restart: no
    container_name: rclone-tautulli
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/tautulli/backups/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/tautulli/"]
  rclone-heimdall:
    image: rclone/rclone
    restart: no
    container_name: rclone-heimdall
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/heimdall/:/mnt/config
    command: ["sync","/mnt/config","jonomega:/Backup/rclone/heimdall"]

