version: "3.3"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - /home/pi/config/config/heimdall:/config
  rclone-heimdall:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-heimdall
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/heimdall/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/heimdall"]
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: vikunja
    volumes:
      - /home/pi/config/config/vikunja/db/:/backup
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
  api:
    image: vikunja/api
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: <a super secure random secret>
      VIKUNJA_SERVICE_FRONTENDURL: http://<your public frontend url with slash>/
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    image: vikunja/frontend
    ports:
      - 82:80
    environment:
      VIKUNJA_API_URL: http://nico:3456/api/v1
    restart: unless-stopped
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: always
    ports: 
      - "8181:8181/tcp"
    environment:
      TZ: 'America/Bogota'
    volumes:
      - /home/pi/config/config/tautulli:/config
  rclone-vikunja-db:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-vikunja-db
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - ./home/pi/config/config/vikunja/db:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/vikunja/db"]
  rclone-vikunja-api:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-vikunja-api
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - ./files:/mnt/config
    command: ["sync","/mnt/config","jonomega:/Backup/rclone/vikunja/api"]
  rclone-pihole:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-pihole
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/pihole-backup/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/pihole1"]
  rclone-pivpn:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-pivpn
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/pivpnbackup/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/pivpn"]
  rclone-tautulli:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-tautulli
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/tautulli/backups/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/tautulli/"]
