global:
  resolve_timeout: 5m
  telegram_api_url: https://api.telegram.org

route:
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: 'YOUR_BOT_TOKEN'
    chat_id: YOUR_CHAT_ID
