services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./data:/updater/data
  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
   alertmanager:
    image: prom/alertmanager
    restart: always
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/prometheus/alertmanager.yml
      - ./templates:/etc/alertmanager/template
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    environment:
       - GF_AUTH_DISABLE_LOGIN_FORM=true
       - GF_AUTH_ANONYMOUS_ENABLED=true
       - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
       - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - 3000:3000
    volumes:
      - /home/pi/config/config/grafana:/var/lib/grafana
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    ports:
      - 3001:3001 
    restart: always
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
    volumes:
      - /home/pi/config/config/uptime-kuma:/app/data
  rclone-uptime-kuma:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-uptime-kuma
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/uptime-kuma/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/uptime-kuma/"]
  rclone-grafana:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-grafana
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/grafana/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/grafana"]
