version: "3"
services:
  ubooquity:
    container_name: ubooquity
    image: linuxserver/ubooquity
    restart: always
    ports: 
      - "2202:2202"
      - "2203:2203"
    volumes:
      - /home/pi/config/:/config
      - /home/pi/Books/:/books
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
      - MAXMEM=1024
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - SUBDOMAINS=jono-ubooquity
      - TOKEN=token
    restart: unless-stopped
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - URL=jono-ubooquity.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=token
    volumes:
      - /home/pi/swag:/config
    ports:
      - 443:443
    restart: unless-stopped
