version: "3.3"
services:
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - SUBDOMAINS=jono-calibre,jono-vpn
      - TOKEN=token
    restart: unless-stopped
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    ports:
      - 3001:3001 
    restart: always
    volumes:
      - /home/pi/config/config/uptime-kuma:/app/data
  chatgpt-bot:
    image: ghcr.io/m1guelpf/chatgpt-telegram
    container_name: chatgpt-telegram
    volumes:
      - /home/pi/config/config/chatgpt-bot:/root/.config
    environment:
      - TELEGRAM_ID=
      - TELEGRAM_TOKEN=
  rclone-uptime-kuma:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-uptime-kuma
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/uptime-kuma/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/uptime-kuma/"]
