version: "3.3"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./data:/updater/data
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    ports:
      - 3001:3001 
    restart: always
    volumes:
      - /home/pi/config/config/uptime-kuma:/app/data
  rclone-uptime-kuma:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-uptime-kuma
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/uptime-kuma/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/uptime-kuma/"]
