version: "3"
services:
  calibre-web:
    container_name: calibre-web
    image: linuxserver/calibre-web:latest
    restart: always
    ports: 
      - "8083:8083"
    volumes:
      - /home/pi/config/:/config
      - /home/pi/Books/:/books
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
      - MAXMEM=1024
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - SUBDOMAINS=jono-calibre,jono-vpn
      - TOKEN=token
    restart: unless-stopped
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - URL=jono-calibre.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=token
    volumes:
      - /home/pi/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
