scrape_configs:
  - job_name: 'wendy'
    metrics_path: /api/prometheus
    scrape_interval: 60s
    static_configs:
      - targets: ['wendy:8123']
    scheme: http
    authorization:
      credentials: "myaccesstoken"
  - job_name: 'donna'
    scrape_interval: 60s
    static_configs:
      - targets: ['donna:9100']
    scheme: http
