scrape_configs:
  - job_name: 'wendy'
    metrics_path: /api/prometheus
    scrape_interval: 60s
    static_configs:
      - targets: ['wendy:8123']
    scheme: http
    authorization:
      credentials: "myaccesstoken"
  - job_name: 'donna'
    scrape_interval: 60s
    static_configs:
      - targets: ['donna:9100']
    scheme: http
  - job_name: 'nico'
    scrape_interval: 60s
    static_configs:
      - targets: ['nico:9100']
    scheme: http
  - job_name: 'yiya'
    scrape_interval: 60s
    static_configs:
      - targets: ['yiya:9100']
    scheme: http
  - job_name: 'plex-local'
    scrape_interval: 60s
    static_configs:
      - targets: ['plex-local:9100']
    scheme: http
  - job_name: 'uptime'
    scrape_interval: 30s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['yiya:3001']
groups:
- name: example
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} de job {{ $labels.job }} está caído."
