global:
  scrape_interval: 3m  
  evaluation_interval: 2m 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

rule_files:
  - "alert_rules.yml"  

scrape_configs:
  - job_name: 'hass'
    metrics_path: /api/prometheus
    scrape_interval: 60s
    static_configs:
      - targets: ['wendy:8123']
    scheme: http
    authorization:
      credentials: "myaccesstoken"
  - job_name: 'wendy'
    scrape_interval: 60s
    static_configs:
      - targets: ['wendy:9100']
  - job_name: 'donna'
    scrape_interval: 60s
    static_configs:
      - targets: ['donna:9100']
    scheme: http
  - job_name: 'nico'
    scrape_interval: 60s
    static_configs:
      - targets: ['nico:9100']
    scheme: http
  - job_name: 'yiya'
    scrape_interval: 60s
    static_configs:
      - targets: ['yiya:9100']
    scheme: http
  - job_name: 'plex-local'
    scrape_interval: 60s
    static_configs:
      - targets: ['plex-local:9100']
    scheme: http
  - job_name: 'uptime'
    scrape_interval: 30s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['yiya:3001']
  - job_name: 'orion'
    scrape_interval: 60s
    static_configs:
      - targets: ['192.168.66.1:9100']
    scheme: http
