version: "3.3"
services:
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: always
    ports: 
      - "8181:8181/tcp"
    environment:
      TZ: 'America/Bogota'
    volumes:
      - /home/pi/config/config/tautulli:/config
  radarr:
    image: linuxserver/radarr
    restart: always
    container_name: radarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    volumes:
      - /home/pi/Videos/Movies:/movies
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/radarr:/config
  sonarr:
    image: linuxserver/sonarr
    restart: always
    container_name: sonarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/Videos/Shows:/tvseries  
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/sonarr:/config
    ports:
      - 8989:8989
  bazarr:
    image: linuxserver/bazarr
    restart: always
    ports:
      - 6767:6767
    volumes:
      - /home/pi/Videos/Movies:/movies
      - /home/pi/Videos/Shows:/tv
      - /home/pi/config/config/bazarr:/config
  readarr:
    image: linuxserver/readarr:develop
    restart: always
    container_name: readarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/Books:/books  
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/readarr:/config
    ports:
      - 8787:8787
  prowlarr:
    image: linuxserver/prowlarr:develop
    restart: always
    container_name: prowlarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/prowlarr:/config
    ports:
      - 9696:9696
  transmission:
    image: linuxserver/transmission
    restart: always
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /home/pi/config/config/transmission:/config
      - /home/pi/completedTorrents:/downloads
  rclone-radarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-radarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/radarr/Backups/scheduled/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/radarr/"]
  rclone-sonarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-sonarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/sonarr/Backups/scheduled/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/sonarr/"]
  rclone-tautulli:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-tautulli
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/tautulli/backups/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/tautulli/"]
  rclone-bazarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-bazarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/bazarr/backup/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/bazarr/"]
  rclone-readarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-readarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/readarr/Backups/scheduled/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/readarr/"]
  rclone-prowlarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-prowlarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/prowlarr/Backups/scheduled/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/prowlarr/"]
  rclone-transmission:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-transmission
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/transmission/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/transmission/"]
