services:
  radarr:
    image: linuxserver/radarr
    restart: always
    container_name: radarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    volumes:
      - /home/pi/Videos/Movies:/movies
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/radarr:/config
    networks:
      - red_interna
  sonarr:
    image: linuxserver/sonarr
    restart: always
    container_name: sonarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/Videos/Shows:/tvseries  
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/sonarr:/config
    ports:
      - 8989:8989
  lidarr:
    image: linuxserver/lidarr
    restart: always
    container_name: lidarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/Music:/music  
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/lidarr:/config
    ports:
      - 8686:8686
  bazarr:
    image: linuxserver/bazarr
    restart: always
    ports:
      - 6767:6767
    volumes:
      - /home/pi/Videos/Movies:/movies
      - /home/pi/Videos/Shows:/tv
      - /home/pi/config/config/bazarr:/config
  prowlarr:
    image: linuxserver/prowlarr:develop
    restart: always
    container_name: prowlarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/prowlarr:/config
    ports:
      - 9696:9696
  transmission:
    image: linuxserver/transmission
    restart: always
    container_name: transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - /home/pi/config/config/transmission:/config
      - /home/pi/completedTorrents:/downloads
    networks:
      - vlanforvpn
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - WEBDRIVER_URL=http://browser-chromium:4444/wd/hub
      - LC_ALL=en_US.UTF-8
    volumes:
      - /home/pi/config/config/changedetection:/config
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      browser-chromium:
         condition: service_started
  browser-chromium:
    hostname: browser-chromium
    image: selenium/standalone-chromium:latest
    ports:
      - 4444:4444
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
  rclone-radarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-radarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/radarr/Backups/scheduled/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/radarr/"]
  rclone-sonarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-sonarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/sonarr/Backups/scheduled/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/sonarr/"]
  rclone-lidarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-lidarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/lidarr/Backups/scheduled/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/lidarr/"]
  rclone-bazarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-bazarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/bazarr/backup/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/bazarr/"]
  rclone-prowlarr:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-prowlarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/prowlarr/Backups/scheduled/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/prowlarr/"]
  rclone-transmission:
    image: rclone/rclone
    restart: on-failure
    container_name: rclone-transmission
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/transmission/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/transmission/"]
  rclone-changedetection:
    image: rclone/rclone
    restart: no
    container_name: rclone-changedetection
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/changedetection/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/changedetection"]
networks:
  vlanforvpn:
    external: true
  red_interna:
    driver: bridge

