version: "3"
services:
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: always
    ports: 
      - "8181:8181/tcp"
    environment:
      TZ: 'America/Bogota'
    volumes:
      - /home/pi/config/config/tautulli:/config
  radarr:
    image: linuxserver/radarr
    restart: always
    container_name: radarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    volumes:
      - /home/pi/Videos/Movies:/movies
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/radarr:/config
  sonarr:
    image: linuxserver/sonarr
    restart: always
    container_name: sonarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/Videos/Shows:/tvseries  
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/sonarr:/config
    ports:
      - 8989:8989
  bazarr:
    image: linuxserver/bazarr
    restart: always
    ports:
      - 6767:6767
    volumes:
      - /home/pi/Videos/Movies:/movies
      - /home/pi/Videos/Shows:/tv
      - /home/pi/config/config/bazarr:/config
  readarr:
    image: linuxserver/readarr:nightly
    restart: always
    container_name: readarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/Books:/books  
      - /home/pi/completedTorrents:/downloads
      - /home/pi/config/config/readarr:/config
    ports:
      - 8787:8787
  rclone:
    image: rclone/rclone
    restart: always
    container_name: rclone
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/rclone:/config
      - /home/pi/config/config/:/mnt/config
    command: ["copy","/mnt/config","jonomega:/Backup/rclone/"]
  prowlarr:
    image: linuxserver/prowlarr:nightly
    restart: always
    container_name: prowlarr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/config/config/prowlarr:/config
    ports:
      - 9696:9696
